name: Swift-demo

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
        
    steps:
      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: 15.0.1
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: "5.3"
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
